### ISSUE TITLE
Partials should be underscored?

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/drupal-theme-boilerplate#49]
From the **SASS** documentation:

## Partials

If you have a SCSS or Sass file that you want to import but don’t want to compile to a CSS file, you can add an underscore to the beginning of the filename. This will tell Sass not to compile it to a normal CSS file. You can then import these files without using the underscore.

For example, you might have `_colors.scss`. Then no `_colors.css` file would be created, and you can do

      @import "colors";

and _colors.scss would be imported.

--

At the moment, Grunt is configured to only compile `styles.scss`. This files imports all the other files, so `styles.scss` should be compiled. All of the other file names should be prefixed with a `_`, because they should not be created. This makes it more clear that these files are not compiled.

**Comment by rob-bar** [comment]
JEP agreed on this one, like that you can identify if the file compiles to css or not based on that underscore. When we change all those files there is no more need for the specify option in the grunt task.
So i guess this is win win.

On another issue: SPEED. When in a late state of a project, compiling to one style.css tends to a longer compile time, lets say over 10secondes, this is not ideal. Maybe we should create 4 files that compile to 
base.css, components.css, layout.css, fallback.css. To increase the speed on those compilations.

```scss

// charset
@charset "UTF-8";

// gems
@import "compass";
@import "h5bp";
@import "susy";

// lib
@import "lib/var";
@import "lib/mixin";

// Styles
@import "base";
@import "component";
@import "layout";
@import "fallback";
```

**Comment by sqndr** [comment]
#44 is hopefully going to be a huge win in speed. :)

**Comment by rob-bar** [comment]
This goes paired with the specify option in grunt, when we do add those underscores, the option can be removed
