### ISSUE TITLE
remove crosscheck logo

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/drupal-theme-boilerplate#53]
https://github.com/Crosscheck/drupal-theme-boilerplate/blob/omega/assets/img/sprite/logo.png

**Comment by rob-bar** [comment]
@cdooms graag ook een logo toevoegen, iets wat losstaat van drupal maar wel bij logo van one agency hoort. Je mag dat als screenshot.png in de root zetten van de omega branch. en maak ook een vierkante versie als je wil. [voorbeeld](http://dl.getdropbox.com/u/7422112/screenshots/Screen%20Shot%202015-01-30%20at%2014.10.32.png) die screenshot komt hier in de admin van drupal.

**Comment by cdooms** [comment]
New logo in the issue-53 branch.
