### ISSUE TITLE
Prefer single quotes or double quotes

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/drupal-theme-boilerplate#54]
Currently the back-end developers use single quotes as the coding standard, while everything in the front-end (javascript and scss) uses double quotes. It would be nice if we could all use the same default. This makes it more easy for "all-round" developers when developing on a project. 

**Note:** All of the Javascript in Drupal core is also written using single quotes where possible. 

> Drupal does not have a hard standard for the use of single quotes vs. double quotes. Where possible, keep consistency within each module, and respect the personal style of other developers.

**Comment by driesd** [comment]
I prefer single quotes in javascript.

**Comment by rob-bar** [comment]
No opinion, prefer both...

**Comment by cdooms** [comment]
No opinion.

**Comment by rob-bar** [comment]
http://stackoverflow.com/questions/242813/when-to-use-double-or-single-quotes-in-javascript

**Comment by rob-bar** [comment]
@sqndr  can you take a final look at this

**Comment by sqndr** [comment]
Again, this is for consistency (front-end / back-end). I'd prefer single quotes because of that reason.

**Comment by rob-bar** [comment]
I think that consistency between 2 different programming languages is something that shouldn't be considered.
php yes single quotes, js no double quotes, check the link why.
Jquery is using doubles, json is using doubles, elimination of bad html code mudding up js files (not in the form of templates).@driesd example of this morning.
All previous boilerplate projects use doubles, I think we should keep consistency on that level.

**Comment by sqndr** [comment]
I think that consistency between 2 different programming languages is something that shouldn't be considered.

=> It's about the consistency in the **system**. Drupal uses single quotes everywhere. Even the omega base theme that we use has single quotes. Since we can use single quotes in javascript, why be different?

php yes single quotes

=> PHP, single quotes = literal string / double quotes => parsed string (huge difference)

All previous boilerplate projects use doubles

=> … which just means that nobody made an issue out of it.

---

Since this is a Drupal boilerplate, preferring single quotes to be consistent. 

---

**Comment by rob-bar** [comment]
I can see your point. I'm sure you can see mine as well.
We all know this is still a minor issue, we should not focus on this.
But more opinions are needed, can everyone comment with 'single" or "double" based on your opinion,
this ticket must be closed before the milestone due date:
@driesd @cdooms @sqndr @Mschuddings, @klaasvw , @c31ck 
@imot3k @sawirah @algeronwaterschoot @heipenberg @kimkennof-dp 
**please only reply with 'single' or "double", to get your vote counted.**

**Comment by klaasvw** [comment]
"All of the Javascript in Drupal core is also written using single quotes where possible."

Since this is about Drupal themes there's absolutely no reason to debate this. We follow the Drupal standard when developing code used within a Drupal application.

**Comment by kimkennof-dp** [comment]
http://s.quickmeme.com/img/25/25c17af0b98cf8e06ad2550b2efd107a67990dd1938942ab2f11de68a9800652.jpg

**Comment by rob-bar** [comment]
Single quotes it is! Drupal decides! I will split this ticket in 2 tickets, one for js and one for scss.
