### ISSUE TITLE
Rename scsslint.yml to .scss-lint.yml

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/drupal-theme-boilerplate#58]
Most editors look by default for a `.scss-lint.yml` file.

**Comment by rob-bar** [comment]
@driesd  Let wel op dat de gruntfile config: "scsslint.yml" ook naar config: "scss-lint.yml" veranderd.
Ik zal dat nog bi jcommitten.

**Comment by rob-bar** [comment]
This can be closed
