### ISSUE TITLE
Add region.tpl.php

### ISSUE THREAD

**Issue by sqndr** [Crosscheck/drupal-theme-boilerplate#60]
Currently, we don't have a region template file and we use the default `system` module template file. Inside the page template however, we wrap all regions inside a `div`, such as `l-header`. This causes two wrappers, because the region templates wraps all the content inside a div as well. So, let's simply include a region.tpl.php with:

        <?php print $content; ?>

This will remove the additional wrapper.

**Comment by rob-bar** [comment]
This is merged and can be closed
